# Generated by Django 3.0.1 on 2020-01-07 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_auto_20190830_1957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiddlwareNotification',
        ),
    ]
